#!/usr/bin/env bash
set -euo pipefail

. /run/dim-agent/environment

case "$#" in
  0) exec /bin/bash --login ;;
  2)
    test "$1" = -c || exit 2
    exec /bin/bash -c "$2"
    ;;
  *) exit 2 ;;
esac
